// D'NEWS sample data — matches reference design (Chile + World mix, Spanish/English)
window.DNEWS_STORIES = [
  {
    id: 1, score: 98, urgent: true, breaking: true,
    tags: ["geopolitics"],
    category: "World",
    source: "Reuters", date: "Mar 18, 2026",
    title: "Trump demands seven countries send warships to keep the Strait of Hormuz open",
    summary: "U.S. President Donald Trump has issued a directive for allies to form a naval coalition to police the vital oil waterway amid Iranian threats.",
    why: "The Strait of Hormuz handles 20% of the world's oil supply → Lo que cambió ahora es el giro de la política de EE.UU. hacia el unilateralismo transaccional para la seguridad marítima → Esto obliga a las potencias mundiales a elegir entre unirse a la guerra o arriesgar un colapso energético total.",
    saved: false, hero: true,
  },
  {
    id: 2, score: 98, urgent: true,
    tags: ["world", "Urgent", "World"],
    category: "World",
    source: "Reuters", date: "Mar 18, 2026",
    title: "Conflicto en Hormuz: EE.UU. bombardea sitios de misiles iraníes tras bloqueo naval",
    summary: "Las fuerzas estadounidenses lanzaron ataques aéreos masivos contra posiciones iraníes cerca del Estrecho de Hormuz para reabrir el tráfico de crudo.",
    why: "This matters because months of shadow warfare have escalated into direct military confrontation → today's strikes mark the most significant US intervention in the region since 2003 → this creates an immediate risk of a total regional war that could send oil prices toward $150 per barrel.",
    saved: true,
  },
  {
    id: 3, score: 98, urgent: true,
    tags: ["world", "Urgent", "Geopolitics"],
    category: "World",
    source: "Reuters", date: "Mar 18, 2026", country: "United Arab Emirates",
    title: "Iranian strikes hit near Australian airbase in UAE, Albanese confirms",
    summary: "Prime Minister Anthony Albanese confirmed that Iranian projectiles landed near the Al-Minhad Air Base in the UAE, where Australian personnel are stationed.",
    why: "The UAE has served as a neutral logistics hub for Western forces. Iran striking near Australian assets directly threatens to pull Oceanic and other coalition partners into a kinetic conflict that was previously regional.",
  },
  {
    id: 4, score: 98, urgent: true,
    tags: ["world", "Urgent", "Guerra"],
    category: "World",
    source: "Associated Press", date: "Mar 17, 2026", country: "Middle East",
    title: "Israel confirms death of top Iranian security official in overnight strikes",
    summary: "Israel ha confirmado la eliminación de un alto mando de la Guardia Revolucionaria Iraní durante una incursión aérea que eleva la tensión regional a niveles críticos.",
    why: "Desde el inicio de la guerra con Irán en 2025, el conflicto se ha mantenido en un intercambio de misiles. Este asesinato selectivo rompe el equilibrio táctico, forzando a Irán a una represalia directa que podría cerrar definitivamente el comercio en el Golfo.",
  },
  {
    id: 5, score: 95, breaking: true, urgent: true,
    tags: ["markets", "Urgent"],
    category: "Markets",
    source: "Bloomberg", date: "Mar 19, 2026", country: "Global",
    title: "Brent crude briefly tops US$119 per barrel before pulling back, and stocks sink worldwide",
    summary: "Global oil prices surged to nearly $120 a barrel following Iranian strikes on major gas infrastructure, triggering a massive sell-off in international stock markets.",
    why: "The energy market was already tight due to geopolitical friction → the direct targeting of the world's largest gas reserves has now triggered a global inflationary shock → central banks may be forced to hike rates despite slowing growth.",
    saved: true,
  },
  {
    id: 6, score: 95, breaking: true, urgent: true,
    tags: ["markets", "Urgent", "Economy"],
    category: "Economy",
    source: "Bloomberg", date: "Mar 19, 2026", country: "Global",
    title: "Gas Price Soars 35% After Strikes on Qatar and Iran Energy Hubs",
    summary: "Global natural gas prices spiked following military strikes on the South Pars field in Iran and facilities in Qatar, threatening an unprecedented energy supply crunch.",
    why: "Energy markets were already volatile due to regional tensions → today's direct hits on primary production hubs have removed a significant percentage of global capacity instantly → for Chile, this implies an immediate increase in electricity generation costs and potential pressure on fiscal subsidies for heating.",
  },
  {
    id: 7, score: 94,
    tags: ["markets", "Markets", "Economy"],
    category: "Markets",
    source: "Financial Times", date: "Mar 18, 2026", country: "Global",
    title: "Petróleo supera los US$100 ante la incertidumbre por la guerra en Irán",
    summary: "Los precios del crudo Brent y WTI se dispararon este miércoles luego de que fracasaran los intentos diplomáticos por liberar el Estrecho de Hormuz.",
    why: "This matters because global inflation was finally cooling toward central bank targets → today's price surge threatens a 'second wave' of stagflation → for Chile, this translates to immediate pressure on gas prices and the MEPCO stabilization fund, potentially straining the 2026 fiscal budget.",
  },
  {
    id: 8, score: 95, urgent: true,
    tags: ["politics", "Urgent", "Chile"],
    category: "Chile",
    source: "Reuters", date: "Mar 16, 2026", country: "Chile",
    title: "Chile and United States Sign Historic Critical Minerals Pact to Reduce China Reliance",
    summary: "President José Antonio Kast and the Trump administration signed a joint statement to secure supply chains for copper and lithium.",
    why: "Chile has historically maintained a neutral trade stance as China's primary copper provider → today's pact aligns Chile's strategic resources directly with U.S. national security interests → this will likely trigger retaliatory trade measures from Beijing, Chile's largest trading partner.",
  },
  {
    id: 9, score: 92,
    tags: ["chile", "Politics"],
    category: "Chile",
    source: "Diario Financiero", date: "Mar 14, 2026", country: "Chile",
    title: "Kast Asume Presidencia de Chile y Fusiona Ministerios de Minería y Economía",
    summary: "El recién asumido mandatario José Antonio Kast anunció la unificación de las carteras de Minería y Economía bajo el liderazgo del líder gremial Daniel Mas.",
    why: "Chile operaba con ministerios de Minería y Economía fragmentados, lo que dilataba la aprobación de proyectos mineros por años → hoy la fusión centraliza la política industrial bajo el criterio de competitividad de Daniel Mas → esto acelerará la puesta en marcha de proyectos de cobre clave para el presupuesto nacional de 2027.",
  },
  {
    id: 10, score: 90,
    tags: ["chile", "Politics"],
    category: "Chile",
    source: "24 Horas", date: "Mar 14, 2026", country: "Chile",
    title: "Gobierno de Kast pone urgencia a 20 medidas legislativas y Plan de Reconstrucción",
    summary: "El Presidente José Antonio Kast ingresó al Congreso una batería de proyectos con discusión inmediata enfocados en seguridad y reactivación económica.",
    why: "Tras una semana de gobierno, Kast busca capitalizar su mandato electoral eliminando el estancamiento legislativo. El éxito de estas leyes definirá la gobernabilidad de Chile ante la crisis migratoria y de seguridad inmediata.",
  },
  {
    id: 11, score: 91,
    tags: ["mining", "Chile"],
    category: "Chile",
    source: "Diario Financiero", date: "Mar 13, 2026", country: "Chile",
    title: "NovaAndino lithium venture faces first crisis as Indigenous communities block Atacama access",
    summary: "The Codelco-SQM joint venture is paralyzed today as Lickanantay communities demand a renegotiation of environmental oversight clauses.",
    why: "Chile has spent years building a state-led lithium strategy to attract global EV battery makers → today's blockade threatens the stability of the NovaAndino venture → any prolonged delay will hurt Chile's credibility as a reliable green-energy partner.",
  },
  {
    id: 12, score: 92,
    tags: ["economy", "Chile"],
    category: "Economy",
    source: "Diario Financiero", date: "Mar 12, 2026", country: "Chile",
    title: "Chile's Central Bank Holds Rate at 5% Amid Global Uncertainty",
    summary: "Chile's central bank kept its benchmark interest rate unchanged at 5%, citing persistent inflation risks and volatile global financial conditions.",
    why: "Rate decisions directly affect mortgage costs, business lending, and the Chilean peso's value → impacting everyday prices.",
  },
  {
    id: 13, score: 87,
    tags: ["politics", "Chile"],
    category: "Chile",
    source: "Diario Financiero", date: "Mar 11, 2026", country: "Chile",
    title: "Presidente Kast retira de tramitación el proyecto de negociación colectiva ramal de Boric",
    summary: "El Ejecutivo chileno retiró oficialmente la reforma laboral estrella de la administración anterior, marcando un giro pro-mercado en las relaciones laborales.",
    why: "La negociación ramal fue la promesa central de la coalición de Boric para reducir la desigualdad. Al eliminarla hoy, Kast desmantela el legado laboral del gobierno previo, consolidando un modelo de negociación descentralizado que favorece la flexibilidad empresarial.",
  },
  {
    id: 14, score: 90,
    tags: ["economy"],
    category: "Economy",
    source: "Reuters", date: "Mar 10, 2026", country: "United States",
    title: "US Federal Reserve Signals Possible Rate Cut in June",
    summary: "The Fed minutes hint at a potential easing cycle as inflation continues to converge toward the 2% target faster than expected.",
    why: "A Fed pivot would weaken the dollar globally → emerging market currencies including the Chilean peso would likely strengthen → giving the BCCh more room to navigate its own policy path.",
  },
  {
    id: 15, score: 95,
    tags: ["geopolitics", "World"],
    category: "World",
    source: "Reuters", date: "Mar 16, 2026", country: "Middle East",
    title: "Israel Expands Ground Offensive in Southern Lebanon; Ground Forces Enter New Sectors",
    summary: "IDF announced the expansion of operations into new sectors of southern Lebanon following continued Hezbollah rocket fire.",
    why: "The expansion marks an escalation that risks dragging Iran-backed forces deeper into a regional war and threatens the fragile Israel-Lebanon corridor.",
  },
];

window.DNEWS_MARKETS = [
  { name: "IPSA",     value: "6,842",   change: "+0.47%", up: true },
  { name: "USD/CLP",  value: "923.50",  change: "-0.12%", up: false },
  { name: "Copper",   value: "$4.35",   change: "+1.2%",  up: true },
  { name: "S&P 500",  value: "5,971",   change: "+0.32%", up: true },
  { name: "BTC",      value: "$87,420", change: "-1.8%",  up: false },
  { name: "Lithium",  value: "$12.8K",  change: "+0.3%",  up: true },
];

window.DNEWS_NAV = ["Home", "Chile", "World", "Economy", "Politics", "Markets", "Technology", "Sports"];

window.DNEWS_TRENDING = [
  { rank: 1, label: "Fed Rate Decision",  count: 15 },
  { rank: 2, label: "Copper Prices",       count: 12 },
  { rank: 3, label: "AI Regulation",       count: 11 },
  { rank: 4, label: "Lithium Policy",      count:  8 },
  { rank: 5, label: "Chile Tax Reform",    count:  7 },
  { rank: 6, label: "Climate Summit",      count:  6 },
  { rank: 7, label: "Copa Libertadores",   count:  5 },
  { rank: 8, label: "Renewable Energy",    count:  4 },
];

window.DNEWS_CLUSTERS = [
  {
    id: "energy", title: "Crisis energética en Oriente Medio", count: 8, score: 97, sources: 3, hot: true,
    lead: "Brent crude briefly tops US$119 per barrel before pulling back, and stocks sink worldwide",
    items: [
      { title: "Brent crude briefly tops US$119 per barrel before pulling back, and stocks sink worldwide", source: "Bloomberg", date: "19 Mar 2026" },
      { title: "Gas Price Soars 35% After Strikes on Qatar and Iran Energy Hubs", source: "Bloomberg", date: "19 Mar 2026" },
      { title: "Conflicto en Hormuz: EE.UU. bombardea sitios de misiles iraníes tras bloqueo naval", source: "Reuters", date: "18 Mar 2026" },
      { title: "Petróleo supera los US$100 ante la incertidumbre por la guerra en Irán", source: "Financial Times", date: "18 Mar 2026" },
      { title: "Brent Crude Surges to $106 as Strait of Hormuz Closure Paralyzes Global Supply", source: "Bloomberg", date: "16 Mar 2026" },
      { title: "Trump demands seven countries send warships to keep the Strait of Hormuz open", source: "Reuters", date: "16 Mar 2026" },
      { title: "IEA to release 400 million barrels of emergency oil to tackle global prices", source: "Reuters", date: "16 Mar 2026" },
      { title: "Trump demands seven countries send warships to keep the Strait of Hormuz open", source: "Reuters", date: "16 Mar 2026" },
    ],
  },
  { id: "lithium",  title: "Litio y minería en Chile", count: 4, score: 91, sources: 4, lead: "Chile and United States Sign Historic Critical Minerals Pact to Reduce China Reliance", items: [] },
  { id: "fed",      title: "Política monetaria de la Fed", count: 1, score: 90, sources: 1, lead: "US Federal Reserve Signals Possible Rate Cut in June", items: [] },
  { id: "tax",      title: "Reforma tributaria en Chile", count: 1, score: 87, sources: 1, lead: "Chile Tax Reform Bill Heads to Senate Committee", items: [] },
  { id: "geo",      title: "Conflictos geopolíticos y alianzas", count: 2, score: 95, sources: 2, lead: "Israel Expands Ground Offensive in Southern Lebanon; Ground Forces Enter New Sectors", items: [] },
  { id: "global",   title: "Mercados y economía global", count: 2, score: 94, sources: 2, hot: true, lead: "Gas Price Soars 35% After Strikes on Qatar and Iran Energy Hubs", items: [] },
  { id: "chilefin", title: "Situación financiera en Chile", count: 1, score: 92, sources: 1, lead: "Chile's Central Bank Holds Rate at 5% Amid Global Uncertainty", items: [] },
];
